# Site Settings
title: My Resume
baseurl: '/jt-cv-sample' #change it according to your repository name

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: true

# Tracker
analytics:

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

########################
remote_theme: zkarampa/jt-cv
#theme: jt-cv
